<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <AssemblyName>Hippo.Server</AssemblyName>
    <RootNamespace>Hippo.Server</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ModelContextProtocol.AspNetCore" />
    <PackageReference Include="Npgsql" />
  </ItemGroup>
</Project>
